### ISSUE TITLE
Fairy Ring maps would be amazing

### ISSUE THREAD

**Issue by tristenlammi** [Antipixel/nexus-map#19] opened 2024-04-11 19:41 UTC
Basically this mod but for fairy rings would be awesome

**Comment by groteworld** [comment] 2024-07-19 06:28
Out of scope for this project. Use Better Teleport Menu plugin.

Can close this issue.

**Comment by Cyborger1** [comment] 2024-12-04 22:28
Closing as duplicate of #3.

**Closed as not planned by Cyborger1** 2024-12-04 22:28 UTC
Labels: duplicate
